version: 2.1
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 1c5b2bd21bcb5b2ec6cef1ac6c47761bf5cb0f00b06165874141e1afb2c9e8ef
    docker:
      - image: cimg/node:16.13.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Test install
          command: npm install
      - run:
          name: run all tests
          command: |
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
      - store_artifacts:
          path: coverage
          # prefix: coverage
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       # - build
#       - test
#     requires:
#       - build
# - upload-coverage:
#     requires:
#        - test
